services:
  mongo:
    image: mongo:4.4
    networks:
      - todolistnetwork
    ports:
      - 27017:27017
  web:
    image: web:latest
    build:
      context: ./web
      dockerfile: ./Dockerfile.web
    ports:
      - "80:8080"
    restart: always
    networks:
      - todolistnetwork
    depends_on:
      - api
  api:
    image: api:latest
    build: 
      context: ./api
      dockerfile: ./Dockerfile.api
    networks:
      - todolistnetwork
    ports:
      - 3000:3000

networks:
  todolistnetwork: